name: Build and Deploy to K8s

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set image tag (timestamp)
        id: vars
        run: echo "TAG=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/kimkyunghyun2756/my-docker-app:${{ steps.vars.outputs.TAG }}

      - name: Replace image tag in deployment manifest
        run: |
          sed "s|REPLACE_TAG|${{ steps.vars.outputs.TAG }}|" k8s/deployment.yaml > k8s/deployment.final.yaml

      - name: Set KUBECONFIG
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
      
      - name: Check secret length
        run: echo "${{ secrets.KUBECONFIG }}" | wc -c

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.0'

      - name: Apply deployment
        run: |
          kubectl apply -f k8s/deployment.final.yaml

      - name: Apply service
        run: |
          kubectl apply -f k8s/service.yaml

